---
title: "Question 6"
output: html_document
date: "2023-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
library(reticulate)
library(ggplot2)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(gridExtra)

data = read.csv("Data-projetmodIA-2324.csv")
```

## Including Plots


```{r}
dlog=data[4:15]
data_quant=data[4:14]
data_quant=scale(log(data_quant))
dlog[1:11]=data_quant

data_mel <- dlog[sample(nrow(dlog)), ]


taille_train=round(0.7*nrow(data_mel))
d_train=data_mel[1:taille_train,]
d_test=data_mel[taille_train:nrow(data_mel),]


color <- dlog$TypeEPCI ;color[color=="CC"] <- "black";

color[color=="CA"] <- "red";color[color=="CU"] <- "green"; color[color=="Metropole"] <- "blue"

lda_model <- lda(TypeEPCI ~ .,data=d_train)

# Afficher les résultats de la LDA
print(lda_model)

# Projeter les individus dans les coordonnées de la LDA
lda_coordinates <- predict(lda_model)$x

# Afficher les individus dans le graphique
plot(lda_coordinates[, c(1,2)], pch = 16, main = "LDA Plot",
     xlab = "LD1", ylab = "LD2",col=color)

plot(lda_coordinates[, c(1,3)], pch = 16, main = "LDA Plot",
     xlab = "LD1", ylab = "LD3",col=color)

plot(lda_coordinates[, c(2,3)], pch = 16, main = "LDA Plot",
     xlab = "LD2", ylab = "LD3",col=color)
# Ajouter une légende
#legend("topright", legend = levels(data$Groupe), col = 1:2, pch = 16, title = "Groupes")



predictions <- predict(lda_model, newdata = d_test)
table(vrai_valeur=d_test$TypeEPCI,prediction=predictions$class)


```
```{r}
dlog2=dlog[1:11]
dlog2$ch4_aux=data$ch4_t
dlog2$ch4_t=data$ch4_t>1000



data_mel2 <- dlog2[sample(nrow(dlog2)), ]

taille_train=round(0.7*nrow(data_mel2))
d_train=data_mel2[1:taille_train,]
d_test=data_mel2[taille_train:nrow(data_mel2),]

lda_model <- lda(ch4_t ~ .,data=d_train)




color2 <- dlog2$ch4_t ;color2[color2=="TRUE"] <- "black";

color2[color2=="FALSE"] <- "red"



# Afficher les résultats de la LDA
print(lda_model)

# Projeter les individus dans les coordonnées de la LDA
lda_coordinates <- predict(lda_model)$x
print(lda_coordinates)

vec=c(rep(1,nrow(d_train)))
# Afficher les individus dans le graphique
plot(lda_coordinates[, 1],vec, pch = 16, main = "LDA Plot",
     xlab = "LD1", ylab = "y",col=color2)
# Ajouter une légende
#legend("topright", legend = levels(data$Groupe), col = 1:2, pch = 16, title = "Groupes")

predictions2 <- predict(lda_data, newdata = d_test)
table(vrai_valeur=d_test$ch4_t,prediction=predictions2$class)

```
