---
title: "Test"
output: 
  pdf_document :
    toc : TRUE
    toc_depth : 2
    number_section : TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
library(ggplot2)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(gridExtra)
library(leaflet)
```

```{r}
data <- read.csv("Data-projetmodIA-2324.csv")
# Sélectionner les colonnes pertinentes (code_epci, latit, longit)
donnees_polluant <- subset(data, select = c(code_epci, annee_inv, nox_kg, so2_kg, pm10_kg, nh3_kg, ges_teqco2, ch4_t, co2_t, n2o_t, latit, longit))

# Afficher les premières lignes de la nouvelle variable
head(donnees_polluant)
```

```{r}
# Liste des polluants
polluants <- c("nox_kg", "so2_kg", "pm10_kg", "nh3_kg", "ges_teqco2", "ch4_t", "co2_t", "n2o_t")

data_polluant <- subset(data, select = c(code_epci, nox_kg, latit, longit))
summary(data_polluant)
```


```{r}
# Sélectionner le polluant que vous souhaitez visualiser
polluant <- "nox_kg"  # Remplacez par le polluant de votre choix

# Créer une carte avec des marqueurs représentant la concentration du polluant
carte_polluant <- leaflet(donnees_polluant) %>%
  addTiles() %>%
  addCircleMarkers(
    radius = 3,
    lng = ~longit,
    lat = ~latit,
    popup = ~paste("EPCI: ", code_epci, "<br>", polluant, ": ", get(polluant))
  )

# Afficher la carte
carte_polluant
```









